// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otfouzqwwlgcbbemsegh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90Zm91enF3d2xnY2JiZW1zZWdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNjEwMTMsImV4cCI6MjA3MjgzNzAxM30.BdhK53qTfdsCUgju7D5b59LpYJR_L5BWsrH36GpmcBk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});